#!/usr/bin/env bash
# Writes hooks/write-tools.txt: every PostHog MCP tool whose readOnlyHint is
# false, read from the tool registry on PostHog/posthog master. The exec write
# gate treats a tool on this list as a write before it falls back to its verb
# regex. Requires curl and jq.
set -euo pipefail

REGISTRY_URL="https://raw.githubusercontent.com/PostHog/posthog/master/services/mcp/schema/tool-definitions-all.json"
HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/../hooks/write-tools.txt"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    echo "# Generated by scripts/generate-write-tools.sh from PostHog/posthog master. Do not edit by hand."
    curl -fsSL --retry 2 --retry-delay 3 "$REGISTRY_URL" \
        | jq -r 'to_entries[] | select(.value.annotations.readOnlyHint == false) | .key' \
        | LC_ALL=C sort -u
} > "$tmp"

count="$(grep -c -v '^#' "$tmp")"
if (( count < 100 )); then
    echo "refusing to write $OUT: only $count tools parsed from $REGISTRY_URL" >&2
    exit 1
fi
mv "$tmp" "$OUT"
trap - EXIT
echo "wrote $count write tools to $OUT"
